spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
application:
  customers:
    topic:
      name: customers
      partitions: 2
